# Generated by Django 4.2.6 on 2024-04-05 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part_of_body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='boots',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='feet',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='head',
            name='created_by',
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='head')),
                ('description', models.CharField(max_length=400)),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.part_of_body')),
            ],
        ),
        migrations.AlterField(
            model_name='gosling',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='main.element'),
        ),
        migrations.AlterField(
            model_name='gosling',
            name='boots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boots', to='main.element'),
        ),
        migrations.AlterField(
            model_name='gosling',
            name='feet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feet', to='main.element'),
        ),
        migrations.AlterField(
            model_name='gosling',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head', to='main.element'),
        ),
        migrations.DeleteModel(
            name='Body',
        ),
        migrations.DeleteModel(
            name='Boots',
        ),
        migrations.DeleteModel(
            name='Feet',
        ),
        migrations.DeleteModel(
            name='Head',
        ),
    ]
