# Generated by Django 4.2.6 on 2024-04-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_part_of_body_remove_boots_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
