# Generated by Django 4.2.6 on 2024-04-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_element_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gosling',
            name='description',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gosling',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
