# Generated by Django 4.2.6 on 2024-04-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gosling_description_gosling_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='description',
        ),
        migrations.RemoveField(
            model_name='element',
            name='is_accepted',
        ),
    ]
