# Generated by Django 4.2.6 on 2024-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_element_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gosling',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
